steps:

# Build the Java artifact
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
    
# Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/spring-gcp-sql-storage/spring-cloud-gcp-logging-masterclass/spring-cloud-gcp-logging-image:latest', '.']
    
# Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/spring-gcp-sql-storage/spring-cloud-gcp-logging-masterclass/spring-cloud-gcp-logging-image:latest']
    
# Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'spring-cloud-gcp-logging-image', '--image', 'asia-south1-docker.pkg.dev/spring-gcp-sql-storage/spring-cloud-gcp-logging-masterclass/spring-cloud-gcp-logging-image:latest', '--region', 'asia-south1']
    
# Logs capture in cloud logging
options:
  logging: CLOUD_LOGGING_ONLY